---
title: "Project_test-code"
author: "Ken Vu"
date: "`r Sys.Date()`"
output: pdf_document
---

Code to screw around with the data set.
```{r}
library(pacman)
p_load(dplyr, ggplot2, readr)
```

# Loading in Data Set (Skip if Done)
Getting in women in stem data
```{r}
women_stem <- read_csv("women-stem.csv")
women_stem
```

Getting in `recent_grad` data set
```{r}
recent_grads <- read_csv("recent-grads.csv")
recent_grads
```


## Merging the two data sets by major
```{r}
full_data <- women_stem %>%
  inner_join(recent_grads %>% 
               select(Major, Employed, Unemployed, 
                      Unemployment_rate), by="Major")
full_data
```

# EDA
```{r}
dat_stats <- full_data %>%
  group_by(Major_category) %>%
  summarise(TotalEmployed=sum(Employed),
            TotalUnemployed=sum(Unemployed),
            Prop_Employed=TotalEmployed/(TotalEmployed + TotalUnemployed),
            Prop_Unemployed=TotalUnemployed/(TotalEmployed + TotalUnemployed))
dat_stats
```

The data for unemployment rate by major category
```{r}
dat_stats1 <- full_data %>%
  group_by(Major_category) %>% 
  summarise(UnemploymentRate=sum(Unemployed)/sum(Employed))
dat_stats1
```

Plot for unemployment rate by category
```{r}
dat_stats1 %>%
  ggplot(aes(x=Major_category,y=UnemploymentRate, 
             fill=Major_category)) + 
  stat_summary(geom="bar")
```

